### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by berndbischl** [mbq/feast_r#1]
hi,
i was just linked to your project. i see that development seemed to have stopped one year ago?
or is this still active?

i am the main developer of mlr here

https://github.com/mlr-org/mlr

and we would be interested to support FEAST in mlr as a fast and flexible way to perform feature filtering.

how much would be missing to release this in CRAN?
do you maybe need some help?

@smilesun @ajing

**Comment by mbq** [comment]
I tried posting on CRAN, but I was not able to get the licensing part correct. Also FEAST is a pretty low-quality software (tons of redundant code, doubles holding integers, calculating expensive values over and over), so my motivation is not too strong.

If you wish, I would be happy to handle it over.

**Comment by Craigacp** [comment]
I fixed the doubles holding integers and removed some of the redundant code in v2. If you have more pointers on redundant code that could be refactored out in ANSI C I'm happy to do that too. I'm interested to know where it calculates expensive values multiple times as I thought I'd got rid of most of them.

**Comment by mbq** [comment]
Sorry, I missed those updates. Another reason not to maintain the interface 😕

**Comment by Craigacp** [comment]
I'm happy to take an R interface into the main FEAST project (v2 already has a COMPILE_R flag to turn off things that the R interface found problematic), but I don't have any experience developing with the R -> C interface. 

The v2 interfaces are cleaner as there is a straightforward entry point for integer values in C so you can do discretisation in the host language, so hopefully it wouldn't be complicated. It currently has Matlab/Octave & Java interfaces and I plan to add Python when I find the time.

**Comment by ajing** [comment]
@Craigacp I am currently trying to write the R interface. What should I look into? The files located in src folder?

**Comment by Craigacp** [comment]
You should try and wrap the C API expressed in the include/FEAST/FSAlgorithms.h and WeightedFSAlgorithms.h files. Have a look at the Java and Matlab interfaces, they are both pretty similar. The surface language passes in the data and labels (and optionally weights) along with a flag that specifies the algorithm to run. Then in the C code for each language (FSToolboxMex.c or FEASTJNI.c) it takes the flag, unpacks and checks the arguments, then calls out the appropriate algorithm. The Matlab version is still calling into the functions that discretise things first (so the inputs are doubles) whereas the Java version calls the integer functions directly.

**Comment by mbq** [comment]
So, like, there is a few options:

1. **Update praznik to FEAST v2 and try to publish on CRAN**; @Craigacp has a best chance to do this, as he holds the FEAST/MIToolbox copyright. Also, this form is nice for the R user since praznik has MIToolbox and FEAST packaged in (with a few hacks to strip the redundant code during linking), so installing everything is just a matter of one `install.packages()`/`install_github()` call. Most likely I would have done this eventually, but currently I don't have too much time.
2.  **Update FEAST (i.e. Craigacp/FEAST) to be able to build R package**; quite likely most natural for @Craigacp, yet installing is more troublesome if you have to build MIToolbox, then FEAST with some R flag, then `install.packages` from a tar.gz or zip or whatever.
3. **Use https://github.com/alecuba16/FEASTR**; which involves @alecuba16.
4. **Write something new**, which seems a bit nonsense provided so much work is already done.

Anyhow, R has a built-in categorical variable type (`factor`), thus I think the interface API shall require the input to be a data.frame of factors and a factor y, with a tip that continuous features can be factorised with the *10-bins heuristic* (this is just `cut(x,10)` in R). Then, the underlying code could not only get input as integers, but also just check the length of the `levels` attribute to get the count of possible values.

**Comment by berndbischl** [comment]
hi all,

ok. 

Let us go though the options: 

1) So  @ @alecuba16 seems to be out, and has no resources to work on this.

2) It seems like the same holds for you @mbq. 

3) I have quite some experience in R, C, and the R/C API. I dont think it will be very hard to wrap FEAST, I already tried this out for a few functions.

4) If we do this, I would rather do this in a separate repo that we control and where we can also create the R API in a format that is consistent with our other projects. 
@mbq But I am up for discussion for this. We could also do this in the main FEAST repo. 
What do you think?

5) @mbq I have read the licence info of FEAST. There would really be no problem to include your sources in a new R package on CRAN, correct? We just have to correctly reference and attribute your work? Which we would have done anyhow.

**Comment by Craigacp** [comment]
My main concern with the current approach in praznik is that it has a modified copy of the FEAST/MIToolbox C sources in it's repo. This isn't for licensing or copyright reasons (it's BSD licensed to allow people to do whatever they want), it's because it effectively forks the FEAST C library and I don't have enough time to maintain and debug divergent versions of the source code.

I'm happy to make changes to the C code for R and ifdef them on or off depending on what wrapper library is being compiled, but I'd prefer all those changes to live in the FEAST repo if possible. I don't understand how the CRAN install process works, so if it's not possible to pull it down as a dependent github project (similar to how XGBoost incorporates dmlc-core and rabit) then I'm ok with a copy of the sources existing in the R wrapper repository.

**Comment by berndbischl** [comment]
Of course I am not modifying your C code in a fork. 
And you do you not need to debug this then.

I have currently copied it. I would probably set up a little script that does this, if I would need to update it.
It works without any changing now (well I am trying out only very few examples at the moment) 

Let me understand this a bit better. We can decide the proper place later?

And: Maybe we should take this some place else? Would you also discuss this for 15 min or Skype or Hangout? Less typing for the initial discussion ....

**Comment by Craigacp** [comment]
Sure, but I can't do it during business hours in the US eastern time zone. I'm not allowed to work on FEAST at my current job.

**Comment by berndbischl** [comment]
Saturday? 
I am in German time. Which is 6h ahead of you. So maybe 11:00 EST = 17:00 Germany?

**Comment by Craigacp** [comment]
Sure. My name on Skype is Craigacp.

**Comment by mbq** [comment]
FYI, I have updated praznik to use FEAST 2.0; turns out it was pretty straightforward. Nevertheless, I won't be trying to put this on CRAN, handling BSD license is way too hard for me.

**Comment by ajing** [comment]
Do you want to add FEAST 2.0 to mlr? @berndbischl

**Comment by mbq** [comment]
Going further, I have re-named praznik into feast_r and basically decided to abandon it in its current state (which is pretty usable, though, despite being CRAN-unpublishable).

The praznik name will be soon re-used for a FEAST-like package, though with similar methods re-implemented from scratch, under GPL-3 and with tight R integration.

**Comment by mbq** [comment]
@berndbischl You may be interested in https://github.com/mbq/praznik
